spring.application.name=torneos-frontend

# El frontend corre en 8081 para no chocar con el backend (8080)
server.port=8081

# URL base de la API REST del backend que vamos a consumir
api.url.jugadores=http://localhost:8080/api/jugadores
api.url.torneos=http://localhost:8080/api/torneos

